# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 111, 1081, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.NegTab = QtWidgets.QWidget()
        self.NegTab.setObjectName("NegTab")
        self.InputPic_neg = QtWidgets.QLabel(self.NegTab)
        self.InputPic_neg.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_neg.setScaledContents(True)
        self.InputPic_neg.setObjectName("InputPic_neg")
        self.OutputPic_neg = QtWidgets.QLabel(self.NegTab)
        self.OutputPic_neg.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_neg.setScaledContents(True)
        self.OutputPic_neg.setObjectName("OutputPic_neg")
        self.Browse_button_neg = QtWidgets.QPushButton(self.NegTab)
        self.Browse_button_neg.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_neg.setObjectName("Browse_button_neg")
        self.Apply_button_neg = QtWidgets.QPushButton(self.NegTab)
        self.Apply_button_neg.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_neg.setObjectName("Apply_button_neg")
        self.label_6 = QtWidgets.QLabel(self.NegTab)
        self.label_6.setGeometry(QtCore.QRect(490, 500, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.NegTab, "")
        self.ThresTab = QtWidgets.QWidget()
        self.ThresTab.setObjectName("ThresTab")
        self.InputPic_thres = QtWidgets.QLabel(self.ThresTab)
        self.InputPic_thres.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_thres.setScaledContents(True)
        self.InputPic_thres.setObjectName("InputPic_thres")
        self.OutputPic_thres = QtWidgets.QLabel(self.ThresTab)
        self.OutputPic_thres.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_thres.setScaledContents(True)
        self.OutputPic_thres.setObjectName("OutputPic_thres")
        self.Browse_button_thres = QtWidgets.QPushButton(self.ThresTab)
        self.Browse_button_thres.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_thres.setObjectName("Browse_button_thres")
        self.Apply_button_thres = QtWidgets.QPushButton(self.ThresTab)
        self.Apply_button_thres.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_thres.setObjectName("Apply_button_thres")
        self.layoutWidget_2 = QtWidgets.QWidget(self.ThresTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(420, 500, 248, 56))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.tabWidget.addTab(self.ThresTab, "")
        self.LogTab = QtWidgets.QWidget()
        self.LogTab.setObjectName("LogTab")
        self.OutputPic_log = QtWidgets.QLabel(self.LogTab)
        self.OutputPic_log.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_log.setScaledContents(True)
        self.OutputPic_log.setObjectName("OutputPic_log")
        self.InputPic_log = QtWidgets.QLabel(self.LogTab)
        self.InputPic_log.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_log.setScaledContents(True)
        self.InputPic_log.setObjectName("InputPic_log")
        self.Apply_button_log = QtWidgets.QPushButton(self.LogTab)
        self.Apply_button_log.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_log.setObjectName("Apply_button_log")
        self.Browse_button_log = QtWidgets.QPushButton(self.LogTab)
        self.Browse_button_log.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_log.setObjectName("Browse_button_log")
        self.label_7 = QtWidgets.QLabel(self.LogTab)
        self.label_7.setGeometry(QtCore.QRect(470, 500, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.LogTab, "")
        self.PowTab = QtWidgets.QWidget()
        self.PowTab.setObjectName("PowTab")
        self.OutputPic_pow = QtWidgets.QLabel(self.PowTab)
        self.OutputPic_pow.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_pow.setScaledContents(True)
        self.OutputPic_pow.setObjectName("OutputPic_pow")
        self.InputPic_pow = QtWidgets.QLabel(self.PowTab)
        self.InputPic_pow.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_pow.setScaledContents(True)
        self.InputPic_pow.setObjectName("InputPic_pow")
        self.Browse_button_pow = QtWidgets.QPushButton(self.PowTab)
        self.Browse_button_pow.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_pow.setObjectName("Browse_button_pow")
        self.Apply_button_pow = QtWidgets.QPushButton(self.PowTab)
        self.Apply_button_pow.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_pow.setObjectName("Apply_button_pow")
        self.label_8 = QtWidgets.QLabel(self.PowTab)
        self.label_8.setGeometry(QtCore.QRect(500, 510, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.PowTab, "")
        self.PieceTab = QtWidgets.QWidget()
        self.PieceTab.setObjectName("PieceTab")
        self.OutputPic_piece = QtWidgets.QLabel(self.PieceTab)
        self.OutputPic_piece.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_piece.setText("")
        self.OutputPic_piece.setPixmap(QtGui.QPixmap("source/piece_wise.png"))
        self.OutputPic_piece.setScaledContents(True)
        self.OutputPic_piece.setObjectName("OutputPic_piece")
        self.InputPic_piece = QtWidgets.QLabel(self.PieceTab)
        self.InputPic_piece.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_piece.setScaledContents(True)
        self.InputPic_piece.setObjectName("InputPic_piece")
        self.Browse_button_piece = QtWidgets.QPushButton(self.PieceTab)
        self.Browse_button_piece.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_piece.setObjectName("Browse_button_piece")
        self.Apply_button_piece = QtWidgets.QPushButton(self.PieceTab)
        self.Apply_button_piece.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_piece.setObjectName("Apply_button_piece")
        self.tabWidget.addTab(self.PieceTab, "")
        self.BitPlaneTab = QtWidgets.QWidget()
        self.BitPlaneTab.setObjectName("BitPlaneTab")
        self.OutputPic_bitslice = QtWidgets.QLabel(self.BitPlaneTab)
        self.OutputPic_bitslice.setGeometry(QtCore.QRect(590, 70, 481, 351))
        self.OutputPic_bitslice.setScaledContents(True)
        self.OutputPic_bitslice.setObjectName("OutputPic_bitslice")
        self.InputPic_bitslice = QtWidgets.QLabel(self.BitPlaneTab)
        self.InputPic_bitslice.setGeometry(QtCore.QRect(40, 70, 481, 351))
        self.InputPic_bitslice.setScaledContents(True)
        self.InputPic_bitslice.setObjectName("InputPic_bitslice")
        self.Browse_button_bitslice = QtWidgets.QPushButton(self.BitPlaneTab)
        self.Browse_button_bitslice.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_bitslice.setObjectName("Browse_button_bitslice")
        self.Apply_button_bitslice = QtWidgets.QPushButton(self.BitPlaneTab)
        self.Apply_button_bitslice.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_bitslice.setObjectName("Apply_button_bitslice")
        self.tabWidget.addTab(self.BitPlaneTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 10, 690, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1000, 40, 92, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intensity Transformations Application"))
        self.InputPic_neg.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_neg.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_neg.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_neg.setText(_translate("MainWindow", "Apply"))
        self.label_6.setText(_translate("MainWindow", "s=L−1−r"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NegTab), _translate("MainWindow", "Negative Image"))
        self.InputPic_thres.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_thres.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_thres.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_thres.setText(_translate("MainWindow", "Apply"))
        self.label_9.setText(_translate("MainWindow", "s = 1.0 if r > threshold"))
        self.label_10.setText(_translate("MainWindow", "s = 0.0 if r <= threshold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ThresTab), _translate("MainWindow", "Thresholding"))
        self.OutputPic_log.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_log.setText(_translate("MainWindow", "Input picture"))
        self.Apply_button_log.setText(_translate("MainWindow", "Apply"))
        self.Browse_button_log.setText(_translate("MainWindow", "Browse Image"))
        self.label_7.setText(_translate("MainWindow", "s=clog(1+r)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LogTab), _translate("MainWindow", "Logarithmic Transformations"))
        self.OutputPic_pow.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_pow.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_pow.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_pow.setText(_translate("MainWindow", "Apply"))
        self.label_8.setText(_translate("MainWindow", "s=cr^γ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PowTab), _translate("MainWindow", "Power Law Transformations"))
        self.InputPic_piece.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_piece.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_piece.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PieceTab), _translate("MainWindow", "Piecewise Linear Transformation"))
        self.OutputPic_bitslice.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_bitslice.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_bitslice.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_bitslice.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BitPlaneTab), _translate("MainWindow", "Bit Plane Slicing"))
        self.label.setText(_translate("MainWindow", "Intensity Transformations Application"))
        self.label_2.setText(_translate("MainWindow", "Image Processing Project"))
        self.label_3.setText(_translate("MainWindow", "Quang Duy"))
        self.label_4.setText(_translate("MainWindow", "Diem Trinh"))
        self.label_5.setText(_translate("MainWindow", "Minh Duc"))
