# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 111, 1081, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.AvgTab = QtWidgets.QWidget()
        self.AvgTab.setObjectName("AvgTab")
        self.InputPic_avg = QtWidgets.QLabel(self.AvgTab)
        self.InputPic_avg.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_avg.setScaledContents(True)
        self.InputPic_avg.setObjectName("InputPic_avg")
        self.OutputPic_avg = QtWidgets.QLabel(self.AvgTab)
        self.OutputPic_avg.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_avg.setScaledContents(True)
        self.OutputPic_avg.setObjectName("OutputPic_avg")
        self.Browse_button_avg = QtWidgets.QPushButton(self.AvgTab)
        self.Browse_button_avg.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_avg.setObjectName("Browse_button_avg")
        self.Apply_button_avg = QtWidgets.QPushButton(self.AvgTab)
        self.Apply_button_avg.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_avg.setObjectName("Apply_button_avg")
        self.label_6 = QtWidgets.QLabel(self.AvgTab)
        self.label_6.setGeometry(QtCore.QRect(270, 450, 171, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("source/Screenshot from 2020-06-12 11-31-33.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.avgSize = QtWidgets.QSlider(self.AvgTab)
        self.avgSize.setGeometry(QtCore.QRect(510, 515, 321, 31))
        self.avgSize.setMinimum(1)
        self.avgSize.setMaximum(50)
        self.avgSize.setOrientation(QtCore.Qt.Horizontal)
        self.avgSize.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.avgSize.setObjectName("avgSize")
        self.avgSizeValue = QtWidgets.QLabel(self.AvgTab)
        self.avgSizeValue.setGeometry(QtCore.QRect(950, 520, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.avgSizeValue.setFont(font)
        self.avgSizeValue.setObjectName("avgSizeValue")
        self.label_8 = QtWidgets.QLabel(self.AvgTab)
        self.label_8.setGeometry(QtCore.QRect(850, 520, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.AvgTab, "")
        self.WeightAvgTab = QtWidgets.QWidget()
        self.WeightAvgTab.setObjectName("WeightAvgTab")
        self.InputPic_wavg = QtWidgets.QLabel(self.WeightAvgTab)
        self.InputPic_wavg.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_wavg.setScaledContents(True)
        self.InputPic_wavg.setObjectName("InputPic_wavg")
        self.OutputPic_wavg = QtWidgets.QLabel(self.WeightAvgTab)
        self.OutputPic_wavg.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_wavg.setScaledContents(True)
        self.OutputPic_wavg.setObjectName("OutputPic_wavg")
        self.Browse_button_wavg = QtWidgets.QPushButton(self.WeightAvgTab)
        self.Browse_button_wavg.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_wavg.setObjectName("Browse_button_wavg")
        self.Apply_button_wavg = QtWidgets.QPushButton(self.WeightAvgTab)
        self.Apply_button_wavg.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_wavg.setObjectName("Apply_button_wavg")
        self.label_7 = QtWidgets.QLabel(self.WeightAvgTab)
        self.label_7.setGeometry(QtCore.QRect(400, 460, 191, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("source/weighted_avg.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.WeightAvgTab, "")
        self.GaussTab = QtWidgets.QWidget()
        self.GaussTab.setObjectName("GaussTab")
        self.OutputPic_gauss = QtWidgets.QLabel(self.GaussTab)
        self.OutputPic_gauss.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_gauss.setScaledContents(True)
        self.OutputPic_gauss.setObjectName("OutputPic_gauss")
        self.InputPic_gauss = QtWidgets.QLabel(self.GaussTab)
        self.InputPic_gauss.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_gauss.setScaledContents(True)
        self.InputPic_gauss.setObjectName("InputPic_gauss")
        self.Apply_button_gauss = QtWidgets.QPushButton(self.GaussTab)
        self.Apply_button_gauss.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_gauss.setObjectName("Apply_button_gauss")
        self.Browse_button_gauss = QtWidgets.QPushButton(self.GaussTab)
        self.Browse_button_gauss.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_gauss.setObjectName("Browse_button_gauss")
        self.tabWidget.addTab(self.GaussTab, "")
        self.MedTab = QtWidgets.QWidget()
        self.MedTab.setObjectName("MedTab")
        self.OutputPic_med = QtWidgets.QLabel(self.MedTab)
        self.OutputPic_med.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_med.setScaledContents(True)
        self.OutputPic_med.setObjectName("OutputPic_med")
        self.InputPic_med = QtWidgets.QLabel(self.MedTab)
        self.InputPic_med.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_med.setScaledContents(True)
        self.InputPic_med.setObjectName("InputPic_med")
        self.Browse_button_med = QtWidgets.QPushButton(self.MedTab)
        self.Browse_button_med.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_med.setObjectName("Browse_button_med")
        self.Apply_button_med = QtWidgets.QPushButton(self.MedTab)
        self.Apply_button_med.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_med.setObjectName("Apply_button_med")
        self.medSizeValue = QtWidgets.QLabel(self.MedTab)
        self.medSizeValue.setGeometry(QtCore.QRect(810, 530, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.medSizeValue.setFont(font)
        self.medSizeValue.setObjectName("medSizeValue")
        self.medSize = QtWidgets.QSlider(self.MedTab)
        self.medSize.setGeometry(QtCore.QRect(280, 525, 411, 31))
        self.medSize.setMinimum(1)
        self.medSize.setMaximum(50)
        self.medSize.setOrientation(QtCore.Qt.Horizontal)
        self.medSize.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.medSize.setObjectName("medSize")
        self.label_9 = QtWidgets.QLabel(self.MedTab)
        self.label_9.setGeometry(QtCore.QRect(710, 530, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.MedTab, "")
        self.LaplacianTab = QtWidgets.QWidget()
        self.LaplacianTab.setObjectName("LaplacianTab")
        self.OutputPic_lap = QtWidgets.QLabel(self.LaplacianTab)
        self.OutputPic_lap.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_lap.setScaledContents(True)
        self.OutputPic_lap.setObjectName("OutputPic_lap")
        self.InputPic_lap = QtWidgets.QLabel(self.LaplacianTab)
        self.InputPic_lap.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_lap.setScaledContents(True)
        self.InputPic_lap.setObjectName("InputPic_lap")
        self.Browse_button_lap = QtWidgets.QPushButton(self.LaplacianTab)
        self.Browse_button_lap.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_lap.setObjectName("Browse_button_lap")
        self.Apply_button_lap = QtWidgets.QPushButton(self.LaplacianTab)
        self.Apply_button_lap.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_lap.setObjectName("Apply_button_lap")
        self.lapSizeValue = QtWidgets.QLabel(self.LaplacianTab)
        self.lapSizeValue.setGeometry(QtCore.QRect(810, 525, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lapSizeValue.setFont(font)
        self.lapSizeValue.setObjectName("lapSizeValue")
        self.label_10 = QtWidgets.QLabel(self.LaplacianTab)
        self.label_10.setGeometry(QtCore.QRect(710, 525, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lapSize = QtWidgets.QSlider(self.LaplacianTab)
        self.lapSize.setGeometry(QtCore.QRect(280, 520, 411, 31))
        self.lapSize.setMinimum(1)
        self.lapSize.setMaximum(15)
        self.lapSize.setOrientation(QtCore.Qt.Horizontal)
        self.lapSize.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.lapSize.setObjectName("lapSize")
        self.tabWidget.addTab(self.LaplacianTab, "")
        self.SobelTab = QtWidgets.QWidget()
        self.SobelTab.setObjectName("SobelTab")
        self.OutputPic_sob = QtWidgets.QLabel(self.SobelTab)
        self.OutputPic_sob.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_sob.setScaledContents(True)
        self.OutputPic_sob.setObjectName("OutputPic_sob")
        self.InputPic_sob = QtWidgets.QLabel(self.SobelTab)
        self.InputPic_sob.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_sob.setScaledContents(True)
        self.InputPic_sob.setObjectName("InputPic_sob")
        self.Browse_button_sob = QtWidgets.QPushButton(self.SobelTab)
        self.Browse_button_sob.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_sob.setObjectName("Browse_button_sob")
        self.Apply_button_sob = QtWidgets.QPushButton(self.SobelTab)
        self.Apply_button_sob.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_sob.setObjectName("Apply_button_sob")
        self.tabWidget.addTab(self.SobelTab, "")
        self.PrewittTab = QtWidgets.QWidget()
        self.PrewittTab.setObjectName("PrewittTab")
        self.Apply_button_pre = QtWidgets.QPushButton(self.PrewittTab)
        self.Apply_button_pre.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_pre.setObjectName("Apply_button_pre")
        self.OutputPic_pre = QtWidgets.QLabel(self.PrewittTab)
        self.OutputPic_pre.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_pre.setScaledContents(True)
        self.OutputPic_pre.setObjectName("OutputPic_pre")
        self.Browse_button_pre = QtWidgets.QPushButton(self.PrewittTab)
        self.Browse_button_pre.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_pre.setObjectName("Browse_button_pre")
        self.InputPic_pre = QtWidgets.QLabel(self.PrewittTab)
        self.InputPic_pre.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_pre.setScaledContents(True)
        self.InputPic_pre.setObjectName("InputPic_pre")
        self.tabWidget.addTab(self.PrewittTab, "")
        self.GabTab = QtWidgets.QWidget()
        self.GabTab.setObjectName("GabTab")
        self.Apply_button_gab = QtWidgets.QPushButton(self.GabTab)
        self.Apply_button_gab.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_gab.setObjectName("Apply_button_gab")
        self.OutputPic_gab = QtWidgets.QLabel(self.GabTab)
        self.OutputPic_gab.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_gab.setScaledContents(True)
        self.OutputPic_gab.setObjectName("OutputPic_gab")
        self.InputPic_gab = QtWidgets.QLabel(self.GabTab)
        self.InputPic_gab.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_gab.setScaledContents(True)
        self.InputPic_gab.setObjectName("InputPic_gab")
        self.Browse_button_gab = QtWidgets.QPushButton(self.GabTab)
        self.Browse_button_gab.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_gab.setObjectName("Browse_button_gab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 500, 341, 17))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gabLambda = QtWidgets.QSlider(self.layoutWidget_2)
        self.gabLambda.setMinimum(1)
        self.gabLambda.setOrientation(QtCore.Qt.Horizontal)
        self.gabLambda.setObjectName("gabLambda")
        self.horizontalLayout_2.addWidget(self.gabLambda)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.gabLambdaValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.gabLambdaValue.setObjectName("gabLambdaValue")
        self.horizontalLayout_2.addWidget(self.gabLambdaValue)
        self.layoutWidget_3 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(380, 470, 341, 17))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gabTheta = QtWidgets.QSlider(self.layoutWidget_3)
        self.gabTheta.setMinimum(1)
        self.gabTheta.setMaximum(180)
        self.gabTheta.setOrientation(QtCore.Qt.Horizontal)
        self.gabTheta.setObjectName("gabTheta")
        self.horizontalLayout_3.addWidget(self.gabTheta)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.gabThetaValue = QtWidgets.QLabel(self.layoutWidget_3)
        self.gabThetaValue.setObjectName("gabThetaValue")
        self.horizontalLayout_3.addWidget(self.gabThetaValue)
        self.layoutWidget_4 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(380, 500, 341, 17))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gabPsi = QtWidgets.QSlider(self.layoutWidget_4)
        self.gabPsi.setMinimum(1)
        self.gabPsi.setMaximum(180)
        self.gabPsi.setOrientation(QtCore.Qt.Horizontal)
        self.gabPsi.setObjectName("gabPsi")
        self.horizontalLayout_4.addWidget(self.gabPsi)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.gabPsiValue = QtWidgets.QLabel(self.layoutWidget_4)
        self.gabPsiValue.setObjectName("gabPsiValue")
        self.horizontalLayout_4.addWidget(self.gabPsiValue)
        self.layoutWidget_5 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(730, 470, 341, 17))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gabSigma = QtWidgets.QSlider(self.layoutWidget_5)
        self.gabSigma.setMinimum(1)
        self.gabSigma.setMaximum(10)
        self.gabSigma.setOrientation(QtCore.Qt.Horizontal)
        self.gabSigma.setObjectName("gabSigma")
        self.horizontalLayout_5.addWidget(self.gabSigma)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.gabSigmaValue = QtWidgets.QLabel(self.layoutWidget_5)
        self.gabSigmaValue.setObjectName("gabSigmaValue")
        self.horizontalLayout_5.addWidget(self.gabSigmaValue)
        self.layoutWidget_6 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget_6.setGeometry(QtCore.QRect(730, 500, 341, 17))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gabGamma = QtWidgets.QSlider(self.layoutWidget_6)
        self.gabGamma.setMinimum(1)
        self.gabGamma.setMaximum(100)
        self.gabGamma.setOrientation(QtCore.Qt.Horizontal)
        self.gabGamma.setObjectName("gabGamma")
        self.horizontalLayout_6.addWidget(self.gabGamma)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.gabGammaValue = QtWidgets.QLabel(self.layoutWidget_6)
        self.gabGammaValue.setObjectName("gabGammaValue")
        self.horizontalLayout_6.addWidget(self.gabGammaValue)
        self.layoutWidget1 = QtWidgets.QWidget(self.GabTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 470, 341, 17))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gabSize = QtWidgets.QSlider(self.layoutWidget1)
        self.gabSize.setMaximum(50)
        self.gabSize.setOrientation(QtCore.Qt.Horizontal)
        self.gabSize.setObjectName("gabSize")
        self.horizontalLayout.addWidget(self.gabSize)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.gabSizeValue = QtWidgets.QLabel(self.layoutWidget1)
        self.gabSizeValue.setObjectName("gabSizeValue")
        self.horizontalLayout.addWidget(self.gabSizeValue)
        self.tabWidget.addTab(self.GabTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(310, 10, 509, 85))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(1000, 40, 92, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spatial Filtering Application"))
        self.InputPic_avg.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_avg.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_avg.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_avg.setText(_translate("MainWindow", "Apply"))
        self.avgSizeValue.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "Filter Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AvgTab), _translate("MainWindow", "Average Filter"))
        self.InputPic_wavg.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_wavg.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_wavg.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_wavg.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WeightAvgTab), _translate("MainWindow", "Weighted Avg Filter"))
        self.OutputPic_gauss.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_gauss.setText(_translate("MainWindow", "Input picture"))
        self.Apply_button_gauss.setText(_translate("MainWindow", "Apply"))
        self.Browse_button_gauss.setText(_translate("MainWindow", "Browse Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GaussTab), _translate("MainWindow", "Gaussian Filter"))
        self.OutputPic_med.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_med.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_med.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_med.setText(_translate("MainWindow", "Apply"))
        self.medSizeValue.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "Filter Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MedTab), _translate("MainWindow", "Median Filter"))
        self.OutputPic_lap.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_lap.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_lap.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_lap.setText(_translate("MainWindow", "Apply"))
        self.lapSizeValue.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "Filter Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LaplacianTab), _translate("MainWindow", "Laplacian Filter"))
        self.OutputPic_sob.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_sob.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_sob.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_sob.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SobelTab), _translate("MainWindow", "Sobel Filter"))
        self.Apply_button_pre.setText(_translate("MainWindow", "Apply"))
        self.OutputPic_pre.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_pre.setText(_translate("MainWindow", "Browse Image"))
        self.InputPic_pre.setText(_translate("MainWindow", "Input picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PrewittTab), _translate("MainWindow", "Prewitt Filter"))
        self.Apply_button_gab.setText(_translate("MainWindow", "Apply"))
        self.OutputPic_gab.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_gab.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_gab.setText(_translate("MainWindow", "Browse Image"))
        self.label_13.setText(_translate("MainWindow", "Lambda"))
        self.gabLambdaValue.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Theta"))
        self.gabThetaValue.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Psi"))
        self.gabPsiValue.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Sigma"))
        self.gabSigmaValue.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "Gamma"))
        self.gabGammaValue.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Filter Size"))
        self.gabSizeValue.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GabTab), _translate("MainWindow", "Gabor Filter"))
        self.label.setText(_translate("MainWindow", "Spatial Filtering Application"))
        self.label_2.setText(_translate("MainWindow", "Image Processing Project"))
        self.label_3.setText(_translate("MainWindow", "Quang Duy"))
        self.label_4.setText(_translate("MainWindow", "Diem Trinh"))
        self.label_5.setText(_translate("MainWindow", "Minh Duc"))
