# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 111, 1081, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.AvgTab = QtWidgets.QWidget()
        self.AvgTab.setObjectName("AvgTab")
        self.InputPic_avg = QtWidgets.QLabel(self.AvgTab)
        self.InputPic_avg.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_avg.setScaledContents(True)
        self.InputPic_avg.setObjectName("InputPic_avg")
        self.OutputPic_avg = QtWidgets.QLabel(self.AvgTab)
        self.OutputPic_avg.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_avg.setScaledContents(True)
        self.OutputPic_avg.setObjectName("OutputPic_avg")
        self.Browse_button_avg = QtWidgets.QPushButton(self.AvgTab)
        self.Browse_button_avg.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_avg.setObjectName("Browse_button_avg")
        self.Apply_button_avg = QtWidgets.QPushButton(self.AvgTab)
        self.Apply_button_avg.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_avg.setObjectName("Apply_button_avg")
        self.label_6 = QtWidgets.QLabel(self.AvgTab)
        self.label_6.setGeometry(QtCore.QRect(410, 450, 171, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("source/Screenshot from 2020-06-12 11-31-33.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.AvgTab, "")
        self.WeightAvgTab = QtWidgets.QWidget()
        self.WeightAvgTab.setObjectName("WeightAvgTab")
        self.InputPic_wavg = QtWidgets.QLabel(self.WeightAvgTab)
        self.InputPic_wavg.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_wavg.setScaledContents(True)
        self.InputPic_wavg.setObjectName("InputPic_wavg")
        self.OutputPic_wavg = QtWidgets.QLabel(self.WeightAvgTab)
        self.OutputPic_wavg.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_wavg.setScaledContents(True)
        self.OutputPic_wavg.setObjectName("OutputPic_wavg")
        self.Browse_button_wavg = QtWidgets.QPushButton(self.WeightAvgTab)
        self.Browse_button_wavg.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_wavg.setObjectName("Browse_button_wavg")
        self.Apply_button_wavg = QtWidgets.QPushButton(self.WeightAvgTab)
        self.Apply_button_wavg.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_wavg.setObjectName("Apply_button_wavg")
        self.label_7 = QtWidgets.QLabel(self.WeightAvgTab)
        self.label_7.setGeometry(QtCore.QRect(400, 460, 191, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("source/weighted_avg.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.WeightAvgTab, "")
        self.GaussTab = QtWidgets.QWidget()
        self.GaussTab.setObjectName("GaussTab")
        self.OutputPic_gauss = QtWidgets.QLabel(self.GaussTab)
        self.OutputPic_gauss.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_gauss.setScaledContents(True)
        self.OutputPic_gauss.setObjectName("OutputPic_gauss")
        self.InputPic_gauss = QtWidgets.QLabel(self.GaussTab)
        self.InputPic_gauss.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_gauss.setScaledContents(True)
        self.InputPic_gauss.setObjectName("InputPic_gauss")
        self.Apply_button_gauss = QtWidgets.QPushButton(self.GaussTab)
        self.Apply_button_gauss.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_gauss.setObjectName("Apply_button_gauss")
        self.Browse_button_gauss = QtWidgets.QPushButton(self.GaussTab)
        self.Browse_button_gauss.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_gauss.setObjectName("Browse_button_gauss")
        self.tabWidget.addTab(self.GaussTab, "")
        self.MedTab = QtWidgets.QWidget()
        self.MedTab.setObjectName("MedTab")
        self.OutputPic_med = QtWidgets.QLabel(self.MedTab)
        self.OutputPic_med.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_med.setScaledContents(True)
        self.OutputPic_med.setObjectName("OutputPic_med")
        self.InputPic_med = QtWidgets.QLabel(self.MedTab)
        self.InputPic_med.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_med.setScaledContents(True)
        self.InputPic_med.setObjectName("InputPic_med")
        self.Browse_button_med = QtWidgets.QPushButton(self.MedTab)
        self.Browse_button_med.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_med.setObjectName("Browse_button_med")
        self.Apply_button_med = QtWidgets.QPushButton(self.MedTab)
        self.Apply_button_med.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_med.setObjectName("Apply_button_med")
        self.tabWidget.addTab(self.MedTab, "")
        self.LaplacianTab = QtWidgets.QWidget()
        self.LaplacianTab.setObjectName("LaplacianTab")
        self.OutputPic_lap = QtWidgets.QLabel(self.LaplacianTab)
        self.OutputPic_lap.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_lap.setScaledContents(True)
        self.OutputPic_lap.setObjectName("OutputPic_lap")
        self.InputPic_lap = QtWidgets.QLabel(self.LaplacianTab)
        self.InputPic_lap.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_lap.setScaledContents(True)
        self.InputPic_lap.setObjectName("InputPic_lap")
        self.Browse_button_lap = QtWidgets.QPushButton(self.LaplacianTab)
        self.Browse_button_lap.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_lap.setObjectName("Browse_button_lap")
        self.Apply_button_lap = QtWidgets.QPushButton(self.LaplacianTab)
        self.Apply_button_lap.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_lap.setObjectName("Apply_button_lap")
        self.tabWidget.addTab(self.LaplacianTab, "")
        self.SobelTab = QtWidgets.QWidget()
        self.SobelTab.setObjectName("SobelTab")
        self.OutputPic_sob = QtWidgets.QLabel(self.SobelTab)
        self.OutputPic_sob.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_sob.setScaledContents(True)
        self.OutputPic_sob.setObjectName("OutputPic_sob")
        self.InputPic_sob = QtWidgets.QLabel(self.SobelTab)
        self.InputPic_sob.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_sob.setScaledContents(True)
        self.InputPic_sob.setObjectName("InputPic_sob")
        self.Browse_button_sob = QtWidgets.QPushButton(self.SobelTab)
        self.Browse_button_sob.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_sob.setObjectName("Browse_button_sob")
        self.Apply_button_sob = QtWidgets.QPushButton(self.SobelTab)
        self.Apply_button_sob.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_sob.setObjectName("Apply_button_sob")
        self.tabWidget.addTab(self.SobelTab, "")
        self.PrewittTab = QtWidgets.QWidget()
        self.PrewittTab.setObjectName("PrewittTab")
        self.Apply_button_pre = QtWidgets.QPushButton(self.PrewittTab)
        self.Apply_button_pre.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_pre.setObjectName("Apply_button_pre")
        self.OutputPic_pre = QtWidgets.QLabel(self.PrewittTab)
        self.OutputPic_pre.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_pre.setScaledContents(True)
        self.OutputPic_pre.setObjectName("OutputPic_pre")
        self.Browse_button_pre = QtWidgets.QPushButton(self.PrewittTab)
        self.Browse_button_pre.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_pre.setObjectName("Browse_button_pre")
        self.InputPic_pre = QtWidgets.QLabel(self.PrewittTab)
        self.InputPic_pre.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_pre.setScaledContents(True)
        self.InputPic_pre.setObjectName("InputPic_pre")
        self.tabWidget.addTab(self.PrewittTab, "")
        self.GabTab = QtWidgets.QWidget()
        self.GabTab.setObjectName("GabTab")
        self.Apply_button_gab = QtWidgets.QPushButton(self.GabTab)
        self.Apply_button_gab.setGeometry(QtCore.QRect(0, 590, 1079, 23))
        self.Apply_button_gab.setObjectName("Apply_button_gab")
        self.OutputPic_gab = QtWidgets.QLabel(self.GabTab)
        self.OutputPic_gab.setGeometry(QtCore.QRect(590, 140, 441, 311))
        self.OutputPic_gab.setScaledContents(True)
        self.OutputPic_gab.setObjectName("OutputPic_gab")
        self.InputPic_gab = QtWidgets.QLabel(self.GabTab)
        self.InputPic_gab.setGeometry(QtCore.QRect(40, 140, 441, 311))
        self.InputPic_gab.setScaledContents(True)
        self.InputPic_gab.setObjectName("InputPic_gab")
        self.Browse_button_gab = QtWidgets.QPushButton(self.GabTab)
        self.Browse_button_gab.setGeometry(QtCore.QRect(0, 560, 1079, 23))
        self.Browse_button_gab.setObjectName("Browse_button_gab")
        self.tabWidget.addTab(self.GabTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 10, 509, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1000, 40, 92, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spatial Filtering Application"))
        self.InputPic_avg.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_avg.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_avg.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_avg.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AvgTab), _translate("MainWindow", "Average Filter"))
        self.InputPic_wavg.setText(_translate("MainWindow", "Input picture"))
        self.OutputPic_wavg.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_wavg.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_wavg.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WeightAvgTab), _translate("MainWindow", "Weighted Avg Filter"))
        self.OutputPic_gauss.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_gauss.setText(_translate("MainWindow", "Input picture"))
        self.Apply_button_gauss.setText(_translate("MainWindow", "Apply"))
        self.Browse_button_gauss.setText(_translate("MainWindow", "Browse Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GaussTab), _translate("MainWindow", "Gaussian Filter"))
        self.OutputPic_med.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_med.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_med.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_med.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MedTab), _translate("MainWindow", "Median Filter"))
        self.OutputPic_lap.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_lap.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_lap.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_lap.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LaplacianTab), _translate("MainWindow", "Laplacian Filter"))
        self.OutputPic_sob.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_sob.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_sob.setText(_translate("MainWindow", "Browse Image"))
        self.Apply_button_sob.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SobelTab), _translate("MainWindow", "Sobel Filter"))
        self.Apply_button_pre.setText(_translate("MainWindow", "Apply"))
        self.OutputPic_pre.setText(_translate("MainWindow", "Output picture"))
        self.Browse_button_pre.setText(_translate("MainWindow", "Browse Image"))
        self.InputPic_pre.setText(_translate("MainWindow", "Input picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PrewittTab), _translate("MainWindow", "Prewitt Filter"))
        self.Apply_button_gab.setText(_translate("MainWindow", "Apply"))
        self.OutputPic_gab.setText(_translate("MainWindow", "Output picture"))
        self.InputPic_gab.setText(_translate("MainWindow", "Input picture"))
        self.Browse_button_gab.setText(_translate("MainWindow", "Browse Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GabTab), _translate("MainWindow", "Gabor Filter"))
        self.label.setText(_translate("MainWindow", "Spatial Filtering Application"))
        self.label_2.setText(_translate("MainWindow", "Image Processing Project"))
        self.label_3.setText(_translate("MainWindow", "Quang Duy"))
        self.label_4.setText(_translate("MainWindow", "Diem Trinh"))
        self.label_5.setText(_translate("MainWindow", "Minh Duc"))
